<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
    <Version>0.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
    <Resource Include="globe.png" />
    <Resource Include="app_icon.ico" />
    <Resource Include="app_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="WinUI3\**\*.cs" />
    <Page Remove="WinUI3\**\*.xaml" />
    <EmbeddedResource Remove="WinUI3\**\*" />
    <None Remove="WinUI3\**\*" />

    <Compile Remove="RidTestApp\**\*.cs" />
    <EmbeddedResource Remove="RidTestApp\**\*" />
    <None Remove="RidTestApp\**\*" />

    <Compile Remove="WinUIProbe3\**\*.cs" />
    <EmbeddedResource Remove="WinUIProbe3\**\*" />
    <None Remove="WinUIProbe3\**\*" />

    <Compile Remove="WinUIWorkaround\**\*.cs" />
    <EmbeddedResource Remove="WinUIWorkaround\**\*" />
    <None Remove="WinUIWorkaround\**\*" />

    <Compile Remove="WinUIWorkaround2\**\*.cs" />
    <EmbeddedResource Remove="WinUIWorkaround2\**\*" />
    <None Remove="WinUIWorkaround2\**\*" />
  </ItemGroup>

</Project>
